# -*- coding: utf-8 -*-
"""MRM_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P9MXnV4XV7wWdzaYqZFYkFuAIGlld20b
"""

# import yfinance as yf
# import pandas as pd
# from pandas_datareader import data as pdr

# start = "2025-04-20"
# end='2026-04-20'

# # -------------------------
# # 1. MARKET DATA (Yahoo)
# # -------------------------
# tickers = {
#     "WTI": "CL=F"
#     # "NatGas": "NG=F",
#     # "USO": "USO",
#     # "UNG": "UNG"
# }

# market_data = pd.DataFrame()

# for name, ticker in tickers.items():
#     df = yf.download(ticker, start=start,end=end)
#     market_data[name] = df["Close"]

# # -------------------------
# # 2. FUTURES CURVE (simplified)
# # -------------------------
# futures = {
#     "CL1": "CL=F",     # front month
#     "CL2": "CL=F",     # (Yahoo limitation — proxy same)
# }

# futures_data = pd.DataFrame()

# for name, ticker in futures.items():
#     df = yf.download(ticker, start=start)
#     futures_data[name] = df["Close"]

# # -------------------------
# # 3. FUNDAMENTAL DATA (FRED)
# # -------------------------
# # fred_series = {
# #     "Crude_Inventory": "DCOILWTICO",   # WTI spot (proxy if needed)
# #     "NatGas_Storage": "NGSTUS1"
# # }

# # fundamental_data = pd.DataFrame()

# # for name, code in fred_series.items():
# #     try:
# #         df = pdr.DataReader(code, "fred", start)
# #         fundamental_data[name] = df[code]
# #     except:
# #         print(f"Failed: {name}")

# # -------------------------
# # SAVE TO EXCEL
# # -------------------------
# with pd.ExcelWriter("MRM_commodity_data.xlsx") as writer:
#     market_data.to_excel(writer, sheet_name="DATA_MARKET")
#     # futures_data.to_excel(writer, sheet_name="DATA_FUTURES")
#     # fundamental_data.to_excel(writer, sheet_name="DATA_FUNDAMENTAL")

# print("Data saved to Excel")

# import yfinance as yf
# import pandas as pd

# # CL2=F = 2nd month WTI crude futures on Yahoo Finance
# df = yf.download('CL2=F', start='2025-05-07', end='2026-04-20')

# # Keep only relevant columns
# df = df[['Open', 'High', 'Low', 'Close', 'Volume']]
# df.index.name = 'Date'

# print(df)
# df.to_csv('CL2_WTI_data.csv')
# print("Saved to CL2_WTI_data.csv")

"""## Underlying OU dynamics"""

import math
import numpy as np
from scipy.stats import norm
import plotly.graph_objects as go
import plotly.io as pio

pio.renderers.default = "colab"
#pio.renderers.default = "iframe"

# ── CORE OU MATH ──────────────────────────────────────────────────────────────
def get_ou_distribution(theta, mu, sigma, s0, tenor):
    T = tenor / 12
    # Mean and Variance for the Log-Price
    mT = mu + (math.log(s0) - mu) * math.exp(-theta * T)
    vT = sigma * math.sqrt((1 - math.exp(-2 * theta * T)) / (2 * theta))

    # Generate price range for x-axis
    prices = np.linspace(max(1, s0 * 0.01), s0 * 3.5, 800)
    lp = np.log(prices)
    pdf = np.exp(-0.5 * ((lp - mT) / vT) ** 2) / (prices * vT * math.sqrt(2 * math.pi))

    mean = math.exp(mT + 0.5 * vT**2)
    p5 = math.exp(mT + norm.ppf(0.05) * vT)
    p95 = math.exp(mT + norm.ppf(0.95) * vT)

    return prices, pdf, mean, p5, p95

# ── SETTINGS & RANGES ────────────────────────────────────────────────────────
DEFAULTS = dict(theta=3.5, mu=4.3946, sigma=0.47, s0=86.14, tenor=6)

sigma_range = np.linspace(0.1, 1.5, 20)
tenor_range = np.arange(1, 37, 1)
theta_range = np.linspace(0.5, 10.0, 20) # Mean Reversion Speed Range

p_init, pdf_init, m_init, p5_init, p95_init = get_ou_distribution(**DEFAULTS)

# ── FIGURE CONSTRUCTION ──────────────────────────────────────────────────────
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=p_init, y=pdf_init,
    mode="lines",
    line=dict(color="#185FA5", width=3),
    name="Price Probability Density",
    fill='tozeroy',
    fillcolor='rgba(24, 95, 165, 0.1)',
    yaxis="y1"
))

fig.add_trace(go.Scatter(
    x=[m_init, m_init], y=[0, max(pdf_init) * 1.1],
    mode="lines",
    line=dict(color="#D85A30", width=2, dash="dash"),
    name=f"Expected Mean: ${m_init:.2f}",
    yaxis="y1"
))

# ── DYNAMIC SLIDER GENERATOR ────────────────────────────────────────────────
def create_steps(val_list, param_type):
    steps = []
    for val in val_list:
        params = DEFAULTS.copy()
        if param_type == 's': params['sigma'] = val
        elif param_type == 't': params['tenor'] = val
        elif param_type == 'mr': params['theta'] = val # Mean Reversion

        p, pdf, m, p5, p95 = get_ou_distribution(**params)
        max_y = max(pdf)

        step = dict(
            method="update",
            label=f"{val:.1f}" if param_type != 't' else f"{int(val)}m",
            args=[
                {
                    "x": [p, [m, m]],
                    "y": [pdf, [0, max_y * 1.1]],
                    "name": ["Price Probability Density", f"Expected Mean: ${m:.2f}"]
                },
                {
                    "title": f"OU Price Evolution | θ={params['theta']:.1f}, σ={params['sigma']:.2f}, T={params['tenor']}m<br>"
                             f"90% CI: ${p5:.2f} — ${p95:.2f}",
                    "yaxis": {"range": [0, max_y * 1.3], "title": "Probability Density", "nticks": 6},
                }
            ]
        )
        steps.append(step)
    return steps

# ── LAYOUT ──────────────────────────────────────────────────────────────────
fig.update_layout(
    title=dict(
        text=f"OU Price Distribution Evolution<br>90% CI: ${p5_init:.2f} — ${p95_init:.2f}",
        x=0.05, y=0.92
    ),
    xaxis=dict(title="WTI Price ($/bbl)", tickprefix="$", range=[0, 300]),
    yaxis=dict(title="Probability Density", range=[0, max(pdf_init) * 1.3], nticks=6),
    yaxis2=dict(visible=False),
    template="plotly_white",
    height=750, # Increased height to fit 3 sliders
    margin=dict(t=160, b=220, l=80, r=40), # Increased bottom margin
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    sliders=[
        # Slider 1: Volatility
        dict(active=10, pad={"t": 30}, currentvalue={"prefix": "Volatility (σ): "},
             steps=create_steps(sigma_range, 's')),
        # Slider 2: Tenor
        dict(active=5, pad={"t": 110}, currentvalue={"prefix": "Tenor (Months): "},
             steps=create_steps(tenor_range, 't')),
        # Slider 3: Mean Reversion Speed
        dict(active=7, pad={"t": 190}, currentvalue={"prefix": "Reversion Speed (θ): "},
             steps=create_steps(theta_range, 'mr'))
    ]
)

fig.update_layout(annotations=[], shapes=[], images=[])
fig.show()

"""## Term Structure for Vol Spread:"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. DATA PREPARATION
df = pd.read_excel('/content/wti_price.xlsx')
if 'Date,Price' in df.columns:
    df[['Date', 'Price']] = df['Date,Price'].str.split(',', expand=True)
    df = df.drop(columns=['Date,Price'])

df['Date'] = pd.to_datetime(df['Date'])
df['Price'] = pd.to_numeric(df['Price'])
df = df.sort_values('Date').reset_index(drop=True)

# Portfolio Stats ($1M Position)
nominal_value = 1_000_000
df['Returns'] = df['Price'].pct_change()
df['Log_Returns'] = np.log(df['Price'] / df['Price'].shift(1))
df['Portfolio_PnL'] = df['Returns'] * nominal_value
df = df.dropna()

# Volatility & Term Structure
windows = [10, 30, 60, 90]
for w in windows:
    df[f'Vol_{w}d'] = df['Log_Returns'].rolling(window=w).std() * np.sqrt(252)
df['TS_Spread'] = df['Vol_30d'] - df['Vol_90d']

# Historical VaR Levels (Last 252 days)
hist_data = df['Portfolio_PnL'].tail(252).values
vars_dict = {
    '90%': (np.percentile(hist_data, 10), 'orange', 'darkorange'),
    '95%': (np.percentile(hist_data, 5), 'red', 'darkred'),
    '99%': (np.percentile(hist_data, 1), 'black', 'black')
}

# 2. VISUALIZATION (5 Separate Panels)
fig, axs = plt.subplots(5, 1, figsize=(14, 25))

# Plot 1: Volatility Evolution
for w in windows:
    axs[0].plot(df['Date'], df[f'Vol_{w}d'], label=f'{w}d Vol')
axs[0].set_title('WTI Volatility Evolution (Annualized)', fontsize=16)
axs[0].set_ylabel('Volatility')
axs[0].legend(loc='upper left')
axs[0].grid(True, alpha=0.3)

# Plot 2: Term Structure State
axs[1].fill_between(df['Date'], df['TS_Spread'], 0, where=(df['TS_Spread'] > 0),
                    color='salmon', alpha=0.6, label='Backwardation (30>90)')
axs[1].fill_between(df['Date'], df['TS_Spread'], 0, where=(df['TS_Spread'] <= 0),
                    color='lightgreen', alpha=0.6, label='Contango (30<90)')
axs[1].axhline(0, color='black', linewidth=1)
axs[1].set_title('Term Structure State (30d - 90d Spread)', fontsize=16)
axs[1].set_ylabel('Vol Spread')
axs[1].legend(loc='upper left')

# Plots 3, 4, 5: Individual Histograms
for i, (label, (val, color, line_color)) in enumerate(vars_dict.items()):
    ax = axs[i+2]
    n, bins, patches = ax.hist(hist_data, bins=50, color='skyblue', edgecolor='white', alpha=0.7)

    # Highlight the specific tail for this confidence level
    for j in range(len(patches)):
        if bins[j] < val:
            patches[j].set_facecolor(color)

    ax.axvline(val, color=line_color, linestyle='--', linewidth=2, label=f'{label} VaR: ${abs(val):,.0f}')
    ax.set_title(f'WTI Daily Loss Distribution - {label} Confidence ($1M Position)', fontsize=16)
    ax.set_ylabel('Frequency')
    ax.legend()

axs[4].set_xlabel('Daily Portfolio Profit / Loss ($)')
plt.tight_layout(pad=3.0)
plt.show()

"""## Vol regime's for different shocks:"""

import numpy as np
import plotly.graph_objects as go
from scipy import stats

# ── PARAMETERS ─────────────────────────────────────
position = 1_000_000
base_vol = 0.80
TRADING_DAYS = 252
n_sims = 50_000
seed = 42

holding_days = 1

rng = np.random.default_rng(seed)
Z = rng.normal(0, 1, n_sims)

# ── VOL MULTIPLIERS ────────────────────────────────
vol_multipliers = np.arange(0.8, 2.05, 0.1)

# ── HELPERS ───────────────────────────────────────
def daily_vol(vol):
    return vol / np.sqrt(TRADING_DAYS / holding_days)

def compute_pnl(vol):
    return position * (Z * daily_vol(vol))

def compute_var(pnl, conf):
    return -np.percentile(pnl, (1 - conf) * 100)

# ── BASE CASE ─────────────────────────────────────
pnl_base = compute_pnl(base_vol)
var95_base = compute_var(pnl_base, 0.95)
var99_base = compute_var(pnl_base, 0.99)

# ── FIGURE ────────────────────────────────────────
fig = go.Figure()

# Histograms
fig.add_trace(go.Histogram(
    x=pnl_base,
    name="Base (80% vol)",
    opacity=0.55,
    marker=dict(color="blue"),
    histnorm="probability density"
))

pnl_shock_init = compute_pnl(base_vol * 1.0)

fig.add_trace(go.Histogram(
    x=pnl_shock_init,
    name="Shock",
    opacity=0.5,
    marker=dict(color="orange"),
    histnorm="probability density"
))

# ── LEGEND DUMMIES FOR VaR ───────────────────────
fig.add_trace(go.Scatter(
    x=[None], y=[None],
    mode="lines",
    line=dict(color="red", dash="dash"),
    name="Base VaR 95%"
))

fig.add_trace(go.Scatter(
    x=[None], y=[None],
    mode="lines",
    line=dict(color="darkred", dash="dot"),
    name="Base VaR 99%"
))

fig.add_trace(go.Scatter(
    x=[None], y=[None],
    mode="lines",
    line=dict(color="purple", dash="dash"),
    name="Shock VaR 95%"
))

fig.add_trace(go.Scatter(
    x=[None], y=[None],
    mode="lines",
    line=dict(color="black", dash="dot"),
    name="Shock VaR 99%"
))

# ── VaR LINES (SHAPES) ────────────────────────────
def make_shapes(pnl_shock):
    var95_shock = compute_var(pnl_shock, 0.95)
    var99_shock = compute_var(pnl_shock, 0.99)

    return [
        dict(type="line", x0=-var95_base, x1=-var95_base,
             y0=0, y1=1, yref="paper",
             line=dict(color="red", dash="dash")),

        dict(type="line", x0=-var99_base, x1=-var99_base,
             y0=0, y1=1, yref="paper",
             line=dict(color="darkred", dash="dot")),

        dict(type="line", x0=-var95_shock, x1=-var95_shock,
             y0=0, y1=1, yref="paper",
             line=dict(color="purple", dash="dash")),

        dict(type="line", x0=-var99_shock, x1=-var99_shock,
             y0=0, y1=1, yref="paper",
             line=dict(color="black", dash="dot")),
    ]

fig.update_layout(shapes=make_shapes(pnl_shock_init))

# ── SLIDER ────────────────────────────────────────
steps = []

for m in vol_multipliers:
    vol = base_vol * m
    pnl_shock = compute_pnl(vol)

    step = dict(
        method="update",
        args=[
            {"x": [pnl_base, pnl_shock]},
            {
                "shapes": make_shapes(pnl_shock),
                "title": f"Commodity Vol Regime | Multiplier = {m:.1f} | Vol = {vol:.2f}"
            }
        ],
        label=f"{m:.1f}x"
    )
    steps.append(step)

fig.update_layout(
    barmode="overlay",
    title="Commodity PnL Distribution (High Vol Regime)",
    xaxis_title="PnL ($)",
    yaxis_title="Density",
    sliders=[{
        "steps": steps,
        "currentvalue": {"prefix": "Vol Multiplier: "}
    }]
)

fig.show()

"""## VaR PnL for different shocks and base-vols:"""

import numpy as np
import pandas as pd
from scipy import stats

# ── PARAMETERS ─────────────────────────────────────
position = 1_000_000
base_vol = 0.60   # corrected commodity baseline (60%)
TRADING_DAYS = 252

multipliers = np.arange(0.9, 2.05, 0.1)

def daily_vol(vol):
    return vol / np.sqrt(TRADING_DAYS)

def var(position, vol, conf=0.95):
    return position * daily_vol(vol) * stats.norm.ppf(conf)

# baseline risk
base_var_95 = var(position, base_vol, 0.95)
base_var_99 = var(position, base_vol, 0.99)

rows = []

for m in multipliers:

    vol = base_vol * m

    v95 = var(position, vol, 0.95)
    v99 = var(position, vol, 0.99)

    rows.append({
        "Vol Multiplier": round(m, 2),
        "Volatility": round(vol, 3),
        "VaR 95 ($)": round(v95, 2),
        "VaR 99 ($)": round(v99, 2),
        "Δ VaR 95 %": round((v95 / base_var_95 - 1) * 100, 1),
        "Δ VaR 99 %": round((v99 / base_var_99 - 1) * 100, 1),
    })

df = pd.DataFrame(rows)

# ── DARK COLOR SCHEME (risk regime aware) ──────────
def risk_color(val):
    if val < 10:
        return "background-color: #1b4332; color: white; font-weight: bold"  # calm
    elif val < 30:
        return "background-color: #6c584c; color: white; font-weight: bold"  # stress
    elif val < 60:
        return "background-color: #7f5539; color: white; font-weight: bold"  # high stress
    else:
        return "background-color: #7f1d1d; color: white; font-weight: bold"  # crisis

styled = df.style.map(
    risk_color,
    subset=["Δ VaR 95 %", "Δ VaR 99 %"]
).set_properties(**{
    "text-align": "center",
    "font-size": "14px"
})

styled

"""## PDF sims under different assumptions"""

import numpy as np
import plotly.graph_objects as go

# ── CORE SETTINGS ───────────────────────────────────
position = 1_000_000
TRADING_DAYS = 252
n_sims = 20000
seed = 42
rng = np.random.default_rng(seed)

# ── MARKET ASSUMPTIONS ─────────────────────────────
S0, theta = 75, 70

# Increased granularity for smoother "evolution"
kappa_vals = np.linspace(0.5, 5.0, 20)
sigma_vals = np.linspace(0.90, 2.00, 20)
T_vals = np.arange(1, 21, 1) # 1 to 20 days

def simulate_state(kappa, sigma, T):
    dt = 1 / TRADING_DAYS
    S = np.full(n_sims, S0, dtype=np.float64)
    for _ in range(int(T)):
        Z = rng.normal(0, 1, n_sims)
        S += kappa * (theta - S) * dt + sigma * np.sqrt(dt) * Z

    pnl_dist = position * (S - S0) / S0
    v95 = -np.percentile(pnl_dist, 5)
    v99 = -np.percentile(pnl_dist, 1)
    return pnl_dist, v95, v99

# ── INITIAL STATE ───────────────────────────────────
k0, s0, t0 = kappa_vals[10], sigma_vals[10], T_vals[10]
p_init, v95_init, v99_init = simulate_state(k0, s0, t0)

fig = go.Figure()

# Trace 0: Histogram
fig.add_trace(go.Histogram(
    x=p_init,
    histnorm="probability density",
    name="PnL Distribution",
    opacity=0.6,
    marker_color="cornflowerblue",
    nbinsx=100
))

# Trace 1: 95% VaR Line
fig.add_trace(go.Scatter(
    x=[-v95_init, -v95_init], y=[0, 0.0001],
    mode="lines",
    line=dict(color="red", width=3, dash="dash"),
    name="95% VaR"
))

# Trace 2: 99% VaR Line
fig.add_trace(go.Scatter(
    x=[-v99_init, -v99_init], y=[0, 0.0001],
    mode="lines",
    line=dict(color="black", width=3, dash="dot"),
    name="99% VaR"
))

# ── SLIDER GENERATOR ────────────────────────────────
def create_steps(val_list, param_type):
    steps = []
    for val in val_list:
        # Determine parameters based on which slider is moving
        k = val if param_type == 'k' else k0
        s = val if param_type == 's' else s0
        t = val if param_type == 't' else t0

        p, v95, v99 = simulate_state(k, s, t)

        step = dict(
            method="update",
            label=f"{val:.2f}" if param_type != 't' else f"{int(val)}d",
            args=[
                # Update x-data for traces 0, 1, and 2
                {"x": [p, [-v95, -v95], [-v99, -v99]]},
                # Update Title
                {"title": f"OU Model Evolution | κ={k:.2f}, σ={s:.2f}, T={int(t)}d<br>"
                          f"95% VaR: ${v95:,.0f} | 99% VaR: ${v99:,.0f}"}
            ]
        )
        steps.append(step)
    return steps

# ── LAYOUT ──────────────────────────────────────────
fig.update_layout(
    title=f"OU Model Evolution | 95% VaR: ${v95_init:,.0f}",
    xaxis_title="PnL ($)",
    yaxis_title="Density",
    template="plotly_white",
    height=700,
    margin=dict(t=100, b=150),
    # Manual Y-axis range to prevent flickering during simulation
    yaxis=dict(range=[0, 0.00008], autorange=True),
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    sliders=[
        dict(active=10, pad={"t": 50}, currentvalue={"prefix": "Mean Reversion (κ): "},
             steps=create_steps(kappa_vals, 'k')),
        dict(active=10, pad={"t": 130}, currentvalue={"prefix": "Volatility (σ): "},
             steps=create_steps(sigma_vals, 's')),
        dict(active=10, pad={"t": 210}, currentvalue={"prefix": "Tenor (T days): "},
             steps=create_steps(T_vals, 't'))
    ]
)

fig.show()

"""## Scenario Analysis:"""

import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from scipy import stats
import webbrowser, os

# ── constants ────────────────────────────────────────────────────────────────
POSITION      = 1_000_000
TRADING_DAYS  = 252
BASE_WTI      = 86.14
BASE_NG       = 2.68
BASE_VOL      = 0.30
BASE_CORR     = 0.45

N_SIMS = 100_000
SEED   = 42

SEVERITY_COLOR = {
    "LOW": "#22c55e",
    "MODERATE": "#f59e0b",
    "HIGH": "#f97316",
    "SEVERE": "#ef4444",
    "EXTREME": "#dc2626",
}

SCENARIOS_DEF = [
    ("Base", 0, 0, 1.0, 0.00),
    ("Supply Disruption", 30, 15, 2.5, 0.20),
    ("Demand Collapse", -40, -25, 3.0, 0.30),
    ("Vol Regime Shift", -10, -5, 4.0, 0.10),
    ("Corr Breakdown", -20, 20, 1.5, -0.80),
    ("COVID-19 Replica", -65, -30, 5.0, 0.40),
]

# ── core functions ───────────────────────────────────────────────────────────
def mc_var(vol, corr, confidence):
    rng = np.random.default_rng(SEED)

    cov = np.array([
        [vol**2, corr * vol**2],
        [corr * vol**2, vol**2]
    ])

    try:
        L = np.linalg.cholesky(cov)
    except:
        cov += 1e-8 * np.eye(2)
        L = np.linalg.cholesky(cov)

    z = rng.standard_normal((N_SIMS, 2))
    rets = z @ L.T / np.sqrt(TRADING_DAYS)

    pnl = POSITION * (0.6 * rets[:,0] + 0.4 * rets[:,1])

    return -np.percentile(pnl, (1-confidence)*100)


def classify(var_delta):
    if var_delta < 5: return "LOW"
    elif var_delta < 15: return "MODERATE"
    elif var_delta < 25: return "HIGH"
    elif var_delta < 40: return "SEVERE"
    else: return "EXTREME"


def build_df(base_vol, confidence):
    rows = []
    base_var = None

    for name, wti_chg, ng_chg, vol_mult, corr_delta in SCENARIOS_DEF:
        vol = base_vol * vol_mult
        corr = min(0.99, max(-0.99, BASE_CORR + corr_delta))

        var = mc_var(vol, corr, confidence)

        if base_var is None:
            base_var = var

        delta = var - base_var
        severity = classify(delta)

        rows.append({
            "Scenario": name,
            "VaR": var,
            "Delta": delta,
            "Severity": severity,
            "VolMult": vol_mult
        })

    return pd.DataFrame(rows), base_var


# ── build slider frames ──────────────────────────────────────────────────────
vol_grid = np.linspace(0.3, 2.0, 6)  # 30% → 200%
conf_levels = [0.95, 0.99]

frames = []
initial_data = None

for vol in vol_grid:
    for conf in conf_levels:

        df, base_var = build_df(vol, conf)

        trace = go.Bar(
            x=df["Scenario"],
            y=df["VaR"],
            marker_color=[SEVERITY_COLOR[s] for s in df["Severity"]],
            text=[f"${v:,.0f}" for v in df["VaR"]],
            textposition="outside"
        )

        frame_name = f"vol={vol:.2f}_conf={conf}"

        frames.append(go.Frame(
            data=[trace],
            name=frame_name
        ))

        if initial_data is None:
            initial_data = [trace]


# ── figure ───────────────────────────────────────────────────────────────────
fig = go.Figure(
    data=initial_data,
    frames=frames
)

# ── sliders ──────────────────────────────────────────────────────────────────
vol_steps = []
for vol in vol_grid:
    vol_steps.append({
        "label": f"{int(vol*100)}%",
        "method": "animate",
        "args": [[f"vol={vol:.2f}_conf=0.99"],
                 {"mode": "immediate"}]
    })

conf_steps = []
for conf in conf_levels:
    conf_steps.append({
        "label": f"{int(conf*100)}%",
        "method": "animate",
        "args": [[f"vol=0.30_conf={conf}"],
                 {"mode": "immediate"}]
    })

fig.update_layout(
    title="⚡ Commodity VaR Scenario Dashboard",
    template="plotly_dark",

    sliders=[
        {
            "active": 0,
            "currentvalue": {"prefix": "Base Vol: "},
            "steps": vol_steps,
            "pad": {"t": 50}
        },
        {
            "active": 1,
            "currentvalue": {"prefix": "Confidence: "},
            "steps": conf_steps,
            "pad": {"t": 120}
        }
    ]
)

# ── axes ─────────────────────────────────────────────────────────────────────
fig.update_yaxes(title_text="Portfolio VaR ($)", tickprefix="$")
fig.update_xaxes(title_text="Scenario", tickangle=-30)

# ── save ─────────────────────────────────────────────────────────────────────
fig.show()

